/**
 * *****************************************************************************
 * Copyright (C) 2015 Dan Ionita
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * *****************************************************************************
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package e3fraud.gui;

import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Map;
import java.util.concurrent.ExecutionException;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreeSelectionModel;

import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;

import com.hp.hpl.jena.rdf.model.Resource;
import com.mxgraph.model.mxGeometry;
import com.mxgraph.view.mxGraphView;

import design.E3Graph;
import design.E3GraphComponent;
import design.Main;
import design.info.Actor;
import design.info.MarketSegment;
import design.info.ValueActivity;
import e3fraud.model.E3Model;
import e3fraud.tools.GenerationWorkerV2;
import e3fraud.tools.SortingWorker;

/**
 *
 * @author Dan
 */
public class FraudWindow extends javax.swing.JPanel {

    static private final String newline = "\n";
    private JFreeChart chart = null;
    private E3Model baseModel = null;
    private final E3Graph baseGraph;
    private final Main mainFrame;
    private E3Graph graph;
    private E3Model selectedModel;
    private Resource selectedNeed;
    private Resource selectedActor;
    private String selectedNeedString;
    private String selectedActorString;
    private int sortCriteria, groupingCriteria, collusions;
    private boolean generateHidden, generateNonOccurring, generateCollusion;
    private Double gainMin, gainMax, lossMin, lossMax;
    private int needStartValue = 0, needEndValue = 0;
    private final Map<String, Resource> actorsMap;
    private final Map<String, Resource> needsMap;
    private java.util.HashMap<String, java.util.Set<E3Model>> groupedSubIdealModels;
    private ChartPanel chartPanel;
    private ResultObject results;
    private E3GraphComponent graphPanel;
    public static FraudWindow mainWindowInstance;
    private JFrame myFrame;

    /**
     * Creates new form MainWindowV2
     *
     * @param original
     * @param baseModel the model to analyze
     * @param mainFrame the parent frame
     * @param myFrame
     */
    public FraudWindow(E3Graph original, E3Model baseModel, Main mainFrame, JFrame myFrame) {
        this.baseGraph = original;
        this.baseModel = baseModel;
        this.mainFrame = mainFrame;
        this.myFrame = myFrame;
        actorsMap = this.baseModel.getActorsMap();
        needsMap = this.baseModel.getNeedsMap();

        //initiate default settings
        this.generateCollusion = true;
        this.generateHidden = true;
        this.generateNonOccurring = true;
        this.collusions = 1;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fraudTypeButtonGroup = new javax.swing.ButtonGroup();
        mainPane = new javax.swing.JSplitPane();
        topPane = new javax.swing.JSplitPane();
        generationSettingsPanel = new javax.swing.JPanel();
        mainActorLabel = new javax.swing.JLabel();
        mainActorComboBox = new javax.swing.JComboBox<>();
        needLabel = new javax.swing.JLabel();
        needComboBox = new javax.swing.JComboBox<>();
        occuringLabel = new javax.swing.JLabel();
        generationSettingsSeparator1 = new javax.swing.JSeparator();
        needToLabel = new javax.swing.JLabel();
        timesLabel = new javax.swing.JLabel();
        advancedSettingsLabel = new javax.swing.JLabel();
        resultCountLabel = new javax.swing.JLabel();
        generationSettingsLabel = new javax.swing.JLabel();
        generationLayeredPane = new javax.swing.JLayeredPane();
        generateButton = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        needStartField = new javax.swing.JFormattedTextField();
        needEndField = new javax.swing.JFormattedTextField();
        listPane = new javax.swing.JSplitPane();
        listSettingsPanel = new javax.swing.JPanel();
        rankingSettingLabel = new javax.swing.JLabel();
        groupSettingLabel = new javax.swing.JLabel();
        sortComboBox = new javax.swing.JComboBox<>();
        groupComboBox = new javax.swing.JComboBox<>();
        listSettingsSeparator = new javax.swing.JSeparator();
        gainLabel = new javax.swing.JLabel();
        lossLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        lossStartField = new javax.swing.JFormattedTextField();
        gainStartField = new javax.swing.JFormattedTextField();
        gainToLabel = new javax.swing.JLabel();
        lossToLabel = new javax.swing.JLabel();
        lossEndField = new javax.swing.JFormattedTextField();
        gainEndField = new javax.swing.JFormattedTextField();
        SortingAndGroupingLabel = new javax.swing.JLabel();
        FiltersLabel = new javax.swing.JLabel();
        resultScrollPane = new javax.swing.JScrollPane();
        root = new DefaultMutableTreeNode("No models generated yet.");
        treeModel = new DefaultTreeModel(root);
        tree = new javax.swing.JTree(treeModel);
        bottomPane = new javax.swing.JLayeredPane();
        visualizationPane = new javax.swing.JSplitPane();
        chartPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        graphPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        placeholderLabel = new javax.swing.JLabel();

        mainPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        mainPane.setResizeWeight(0.5);

        generationSettingsPanel.setMinimumSize(new java.awt.Dimension(200, 310));
        generationSettingsPanel.setPreferredSize(new java.awt.Dimension(200, 370));

        mainActorLabel.setText("Main actor:");
        mainActorLabel.setToolTipText("The main actor is the trusted actor (usually the one which is coducting the assessment)");

        mainActorComboBox.setModel(new DefaultComboBoxModel(actorsMap.keySet().toArray()));

        needLabel.setText("Need:");
        needLabel.setToolTipText("This is the need that will be parametrized and shown on the x-axis of the profitability chart");

        needComboBox.setModel(new DefaultComboBoxModel(needsMap.keySet().toArray()));

        occuringLabel.setText("occurs");
        occuringLabel.setToolTipText("The range of the x-axis");

        needToLabel.setText("to");

        timesLabel.setText("times");

        advancedSettingsLabel.setForeground(new java.awt.Color(6, 69, 173));
        advancedSettingsLabel.setText("Advanced settings...");
        advancedSettingsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advancedSettingsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advancedSettingsLabelMouseClicked(evt);
            }
        });

        resultCountLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        resultCountLabel.setForeground(new java.awt.Color(102, 102, 102));
        resultCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultCountLabel.setText("0 fraud(s) generated");
        resultCountLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        generationSettingsLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        generationSettingsLabel.setText("Fraud generation");

        generateButton.setForeground(new java.awt.Color(0, 153, 0));
        generateButton.setText("Generate");
        generateButton.setToolTipText("Generate fraud scenarios based on the above settings");
        generateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 51)));
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        progressBar.setStringPainted(true);

        generationLayeredPane.setLayer(generateButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        generationLayeredPane.setLayer(progressBar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout generationLayeredPaneLayout = new javax.swing.GroupLayout(generationLayeredPane);
        generationLayeredPane.setLayout(generationLayeredPaneLayout);
        generationLayeredPaneLayout.setHorizontalGroup(
            generationLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(generationLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 932, Short.MAX_VALUE))
        );
        generationLayeredPaneLayout.setVerticalGroup(
            generationLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(generateButton, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
            .addGroup(generationLayeredPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
        );

        needStartField.setText("1");
        needStartField.setPreferredSize(new java.awt.Dimension(25, 22));

        needEndField.setText("500");
        needEndField.setPreferredSize(new java.awt.Dimension(25, 22));

        javax.swing.GroupLayout generationSettingsPanelLayout = new javax.swing.GroupLayout(generationSettingsPanel);
        generationSettingsPanel.setLayout(generationSettingsPanelLayout);
        generationSettingsPanelLayout.setHorizontalGroup(
            generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generationSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generationSettingsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(generationSettingsPanelLayout.createSequentialGroup()
                        .addGroup(generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(generationSettingsSeparator1)
                            .addGroup(generationSettingsPanelLayout.createSequentialGroup()
                                .addComponent(mainActorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainActorComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(generationSettingsPanelLayout.createSequentialGroup()
                                .addComponent(needLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(needComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(resultCountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(generationLayeredPane)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generationSettingsPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, generationSettingsPanelLayout.createSequentialGroup()
                                        .addComponent(occuringLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(needStartField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addGap(6, 6, 6)
                                        .addComponent(needToLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(needEndField, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(timesLabel))
                                    .addComponent(advancedSettingsLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())))
        );
        generationSettingsPanelLayout.setVerticalGroup(
            generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generationSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(generationSettingsLabel)
                .addGap(18, 18, 18)
                .addGroup(generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainActorLabel)
                    .addComponent(mainActorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(generationSettingsSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(needComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(needLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(generationSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(occuringLabel)
                    .addComponent(needToLabel)
                    .addComponent(needStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(needEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timesLabel))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(generationLayeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultCountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(advancedSettingsLabel)
                .addContainerGap())
        );

        resultCountLabel.getAccessibleContext().setAccessibleName("");
        resultCountLabel.getAccessibleContext().setAccessibleDescription("");
        resultCountLabel.setVisible(false);

        topPane.setLeftComponent(generationSettingsPanel);

        listPane.setResizeWeight(1.0);
        listPane.setFocusTraversalPolicyProvider(true);

        listSettingsPanel.setMinimumSize(new java.awt.Dimension(200, 250));
        listSettingsPanel.setPreferredSize(new java.awt.Dimension(200, 370));

        rankingSettingLabel.setText("Sort by:");

        groupSettingLabel.setText("Group by:");

        sortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loss of main actor", "Gain of other actors" }));

        groupComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "collusion" }));

        gainLabel.setText("Gain of other actors ");

        lossLabel.setText("Loss of main actor");

        refreshButton.setText("Apply");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        lossStartField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));
        lossStartField.setText("0");
        lossStartField.setPreferredSize(new java.awt.Dimension(60, 22));

        gainStartField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));
        gainStartField.setText("0");
        gainStartField.setPreferredSize(new java.awt.Dimension(60, 22));

        gainToLabel.setText("to");

        lossToLabel.setText("to");

        lossEndField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));
        lossEndField.setPreferredSize(new java.awt.Dimension(60, 22));

        gainEndField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.##"))));
        gainEndField.setPreferredSize(new java.awt.Dimension(60, 22));

        SortingAndGroupingLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SortingAndGroupingLabel.setText("Sorting and grouping");

        FiltersLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FiltersLabel.setText("Filters");

        javax.swing.GroupLayout listSettingsPanelLayout = new javax.swing.GroupLayout(listSettingsPanel);
        listSettingsPanel.setLayout(listSettingsPanelLayout);
        listSettingsPanelLayout.setHorizontalGroup(
            listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SortingAndGroupingLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, listSettingsPanelLayout.createSequentialGroup()
                        .addComponent(gainStartField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gainToLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gainEndField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(listSettingsPanelLayout.createSequentialGroup()
                        .addComponent(lossStartField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lossToLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lossEndField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(refreshButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(listSettingsSeparator, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, listSettingsPanelLayout.createSequentialGroup()
                        .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lossLabel)
                            .addComponent(gainLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, listSettingsPanelLayout.createSequentialGroup()
                        .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rankingSettingLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(groupSettingLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(groupComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sortComboBox, 0, 126, Short.MAX_VALUE)))
                    .addComponent(FiltersLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );
        listSettingsPanelLayout.setVerticalGroup(
            listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listSettingsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SortingAndGroupingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rankingSettingLabel)
                    .addComponent(sortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(groupSettingLabel)
                    .addComponent(groupComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(listSettingsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FiltersLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lossLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lossStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lossToLabel)
                    .addComponent(lossEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(gainLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(listSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gainStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gainToLabel)
                    .addComponent(gainEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(refreshButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listPane.setRightComponent(listSettingsPanel);

        resultScrollPane.setName("resultScrollPane"); // NOI18N
        resultScrollPane.setPreferredSize(new java.awt.Dimension(400, 322));
        resultScrollPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                resultScrollPaneComponentResized(evt);
            }
        });

        tree.setRowHeight(0);//hack to make rowHeight adjust to components instead of fixed (stupid LAF)
        tree.setCellRenderer(new CustomTreeCellRenderer(tree));
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        tree.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                treeComponentResized(evt);
            }
        });
        tree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                treeValueChanged(evt);
            }
        });
        resultScrollPane.setViewportView(tree);

        listPane.setLeftComponent(resultScrollPane);

        topPane.setRightComponent(listPane);

        mainPane.setLeftComponent(topPane);

        visualizationPane.setResizeWeight(0.5);

        chartPane.setPreferredSize(new java.awt.Dimension(500, 400));
        chartPane.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Profitability chart <right-click for options>");
        chartPane.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        visualizationPane.setRightComponent(chartPane);
        chartPane.getAccessibleContext().setAccessibleDescription("");

        graphPane.setPreferredSize(new java.awt.Dimension(500, 400));
        graphPane.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                graphPaneComponentResized(evt);
            }
        });
        graphPane.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Model preview <double click to open in editor>");
        graphPane.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        visualizationPane.setLeftComponent(graphPane);

        placeholderLabel.setForeground(new java.awt.Color(102, 102, 102));
        placeholderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        placeholderLabel.setText("< Select a scenario above to see its model and profitability graph here>");
        placeholderLabel.setToolTipText("sdasdsadas");
        placeholderLabel.setPreferredSize(visualizationPane.getPreferredSize());

        bottomPane.setLayer(visualizationPane, javax.swing.JLayeredPane.DEFAULT_LAYER);
        bottomPane.setLayer(placeholderLabel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout bottomPaneLayout = new javax.swing.GroupLayout(bottomPane);
        bottomPane.setLayout(bottomPaneLayout);
        bottomPaneLayout.setHorizontalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualizationPane)
            .addGroup(bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(placeholderLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bottomPaneLayout.setVerticalGroup(
            bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(visualizationPane)
            .addGroup(bottomPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomPaneLayout.createSequentialGroup()
                    .addComponent(placeholderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        visualizationPane.setVisible(false);

        mainPane.setRightComponent(bottomPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPane, javax.swing.GroupLayout.DEFAULT_SIZE, 721, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        readSettings();
        sortAndDisplay();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void treeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_treeValueChanged
        JTree tree = (JTree) evt.getSource();
        //on selection
        if (!tree.isSelectionEmpty()) {
            //enable visualization
            visualizationPane.setVisible(true);
            placeholderLabel.setVisible(false);
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) tree.getLastSelectedPathComponent();
            if (node.getUserObject() instanceof E3Model) {
                //grab the E3Model of the selected row
                selectedModel = (E3Model) node.getUserObject();
                //create a chart 
                chart = ChartGenerator.generateChart(selectedModel, selectedNeed, needStartValue, needEndValue, false);
                //then, 
                // if the chartPanel exists, update it
                if (chartPanel != null) {
                    chartPanel.setChart(chart);
                }//otherwise create one and add it the window
                else {
                    chartPanel = new ChartPanel(chart);
                    chartPane.add(chartPanel);
                    chartPanel.setVisible(true);
                }

                // Remove current e3graph if it's already there
                if (graphPane.getComponentCount() > 1) {
                    graphPane.remove(1);
                }

                //create a graph
                graph = new E3Graph(baseGraph, selectedModel.getFraudChanges());
                System.out.println("CHANGES:");
                System.out.println("\t colludedActors:"+ selectedModel.getFraudChanges().colludedActors);
                System.out.println("\t hiddenTransactions:"+ selectedModel.getFraudChanges().hiddenTransactions);
                System.out.println("\t nonOccurringTransactions:"+ selectedModel.getFraudChanges().nonOccurringTransactions);

                // Then just create a graph panel from scratch
				graphPanel = new E3GraphComponent(graph);
				// Disable right mouse clicks
				graphPanel.setPopupTriggerEnabled(false);
				// Prevent other funny business
				graphPanel.setEnabled(false);
				// Apparently mxGraphControl takes care of mouse business of
				// mxGraph (which is the parent of E3Graph)
				graphPanel.getGraphControl().addMouseListener(new MouseAdapter() {
					@Override
					public void mouseClicked(MouseEvent e) {
						System.out.println("Mouse clicked on graph!");
						// On doubleclick
						if (e.getClickCount() == 2) {
							// Create a new tab with the current graph
							FraudWindow.this.mainFrame.addNewTabAndSwitch(new E3Graph((E3Graph) graphPanel.getGraph(), false));
							// Switch to the screen
							FraudWindow.this.mainFrame.mainFrame.requestFocus();
						}
					}
				});

				// Refresh E3GraphComponent to make sure E3Style is used
				graphPanel.refresh();
				// Add it 
				graphPane.add(graphPanel);  
				// Set it visible if it isn't already
				graphPanel.setVisible(true);

				// Graph scaling code
				// To ensure that the size is not 0
				if (graphPane.getVisibleRect().getWidth() < 10) {
					myFrame.revalidate();
				}
				
				graphPanel.centerAndScaleView(graphPane.getVisibleRect().getWidth(), graphPane.getVisibleRect().getHeight());
				
				// Make the scrollbars disappear
				graphPanel.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_NEVER);
				graphPanel.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_NEVER);
				
				myFrame.revalidate();
            }
        } else {
            visualizationPane.setVisible(false);
            placeholderLabel.setVisible(true);
        }
    }//GEN-LAST:event_treeValueChanged

    private void resultScrollPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_resultScrollPaneComponentResized
        TreeModel oldModel = tree.getModel();
        tree.setModel(null);
        tree.setModel(oldModel);
    }//GEN-LAST:event_resultScrollPaneComponentResized

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        readSettings();
        generateSortAndDisplay();
    }//GEN-LAST:event_generateButtonActionPerformed

    private void advancedSettingsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advancedSettingsLabelMouseClicked
        AdvancedGenerationSettingsDialog dialog = new AdvancedGenerationSettingsDialog(this.myFrame, true, this.generateHidden, this.generateNonOccurring, this.generateCollusion, this.collusions);
        if (dialog.getSettings() != null) {
            this.generateNonOccurring = dialog.getSettings().generateNonOccurring;
            this.generateHidden = dialog.getSettings().generateHidden;
            this.generateCollusion = dialog.getSettings().generateCollusion;
            this.collusions = dialog.getSettings().collusions;
            System.out.println("settings updated");
        }
    }//GEN-LAST:event_advancedSettingsLabelMouseClicked

    private void treeComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_treeComponentResized
    }//GEN-LAST:event_treeComponentResized

    private void graphPaneComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_graphPaneComponentResized
    	if (graphPanel != null && graphPane != null) {
			graphPanel.centerAndScaleView(graphPane.getVisibleRect().getWidth(), graphPane.getVisibleRect().getHeight());
    	
			myFrame.revalidate();
    	}
    }//GEN-LAST:event_graphPaneComponentResized

    private void generateSortAndDisplay() {
        //Have a Worker thread to the time-consuming generation and raking (to not freeze the GUI)
        GenerationWorkerV2 generationWorker = new GenerationWorkerV2(baseModel, selectedActor, selectedNeed, selectedNeedString, needStartValue, needEndValue, generateNonOccurring, generateHidden, generateCollusion, collusions) {
            //make it so that when Worker is done
            @Override
            protected void done() {
                try {
                    //the Worker's result is retrieved
                    groupedSubIdealModels = get();
                    //Progress bar is replaced with button
                    progressBar.setVisible(false);
                    //and the cursor goes back to normal
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    //now sort and display
                    sortAndDisplay();
                    //catch all in case something goes wrong
                } catch (InterruptedException | ExecutionException ex) {
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    generateButton.setVisible(true);
                    System.err.println("Exception encountered during generation: \n" + ex);
                    ex.printStackTrace();
                    PopUps.infoBox("Encountered an error. Most likely out of memory; try increasing the heap size of JVM", "Error");
                }
            }
        };
        //replace generate button with progress bar
        generateButton.setVisible(false);
        progressBar.setVisible(true);
        progressBar.setIndeterminate(true);
        progressBar.setString("generating...");
        //change mouse cursor 
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //and run the worker
        generationWorker.execute();
    }

    private void sortAndDisplay() {
        //Have a Worker thread to the time-consuming generation and raking (to not freeze the GUI)
        SortingWorker rankingWorker = new SortingWorker(groupedSubIdealModels, baseModel, selectedActorString, selectedActor, selectedNeed, selectedNeedString, needStartValue, needEndValue, sortCriteria, groupingCriteria, lossMin, lossMax, gainMin, gainMax) {
            //make it so that when Worker is done
            @Override
            protected void done() {
                try {
                    //The Worker's result is retrieved
                    results = get();
                    //if there are any results to show
                    if (results.getShownResults() > 0) {
                        root = results.getRoot();
                        //Hide root to save space
                        tree.setRootVisible(false);
                        //Update result label 
                        resultCountLabel.setText("Showing " + results.getShownResults() + "/" + results.getTotalResults() + " results");
                    } else {
                        tree.setRootVisible(true);
                        root = new DefaultMutableTreeNode("No results to show (check generation settings or filters)");
                        resultCountLabel.setText("Showing " + results.getShownResults() + "/" + results.getTotalResults() + " results");
                    }
                    //The result tree is populated 
                    treeModel.setRoot(root);
                    tree.setModel(treeModel);
                    tree.updateUI();
                    tree.collapseRow(1);
                    //Replace progress bar with generate button
                    progressBar.setVisible(false);
                    generateButton.setVisible(true);
                    //show result label
                    resultCountLabel.setVisible(true);
                    //The cursor also goes back to normal
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    //catch all in case something goes wrong
                } catch (InterruptedException | ExecutionException ex) {
                    setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
                    System.err.println(ex.getMessage() + "exception encountered during generation: \n");
                    ex.printStackTrace();
                    PopUps.infoBox("Encountered an error. Most likely out of memory; try increasing the heap size of JVM", "Error");
                }
            }
        };
        //attach a listener to the worker in order to update the progress bar
        rankingWorker.addPropertyChangeListener(
                new PropertyChangeListener() {
            public void propertyChange(PropertyChangeEvent evt) {
                if ("progress".equals(evt.getPropertyName())) {
                    progressBar.setValue((Integer) evt.getNewValue());
                }
            }
        });
        //replace generate button with progress bar
        generateButton.setVisible(false);
        progressBar.setVisible(true);
        progressBar.setIndeterminate(false);
        progressBar.setString("sorting...");
        //change mouse cursor 
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //and run the worker
        rankingWorker.execute();
    }

    private void readSettings() {
        needStartValue = Integer.parseInt(needStartField.getText());
        needEndValue = Integer.parseInt(needEndField.getText());
        selectedActorString = mainActorComboBox.getSelectedItem().toString();
        selectedNeedString = needComboBox.getSelectedItem().toString();
        selectedActor = actorsMap.get(selectedActorString);
        selectedNeed = needsMap.get(selectedNeedString);
        sortCriteria = sortComboBox.getSelectedIndex();
        groupingCriteria = groupComboBox.getSelectedIndex();
        gainMin = Double.parseDouble(gainStartField.getText());
        lossMin = Double.parseDouble(lossStartField.getText());
        if (!gainEndField.getText().equals("")) {
            gainMax = Double.parseDouble(gainEndField.getText());
        } else {
            gainMax = Double.MAX_VALUE;
        }
        if (!lossEndField.getText().equals("")) {
            lossMax = Double.parseDouble(lossEndField.getText());
        } else {
            lossMax = Double.MAX_VALUE;
        }
    }

    public void fitMiniGraph() {
        Main.mainFrame.pack();

        mxGraphView view = graphPanel.getGraph().getView();

        double minX = Double.MAX_VALUE, minY = Double.MAX_VALUE;

        for (Object obj : graph.getChildCells(graph.getDefaultParent())) {
            // Only look at the positions from top-level elements
            if (!(graph.getModel().getValue(obj) instanceof ValueActivity
                    || graph.getModel().getValue(obj) instanceof MarketSegment
                    || graph.getModel().getValue(obj) instanceof Actor)) {
                continue;
            }

            mxGeometry gm = graph.getCellGeometry(obj);
            minX = Math.min(minX, gm.getX());
            minY = Math.min(minY, gm.getY());
        }

        double scale = graphPanel.getVisibleRect().getWidth() / view.getGraphBounds().getWidth();
        //System.out.println(scale);

        view.scaleAndTranslate(scale, -minX, -minY);

        graphPanel.refresh();
    }

    /**
     * Create the GUI and show it. For thread safety, this method should be
     * invoked from the event dispatch thread.
     *
     * @param model
     */
    public static void createAndShowGUI(E3Model model) {
        //Create and set up the window.
        JFrame frame = new JFrame("e3fraud");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Add content to the window.
        mainWindowInstance = new FraudWindow(null, model, null, frame);
        frame.setContentPane(mainWindowInstance);

        //Display the window.
        frame.pack();
        frame.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FiltersLabel;
    private javax.swing.JLabel SortingAndGroupingLabel;
    private javax.swing.JLabel advancedSettingsLabel;
    private javax.swing.JLayeredPane bottomPane;
    private javax.swing.JPanel chartPane;
    private javax.swing.ButtonGroup fraudTypeButtonGroup;
    private javax.swing.JFormattedTextField gainEndField;
    private javax.swing.JLabel gainLabel;
    private javax.swing.JFormattedTextField gainStartField;
    private javax.swing.JLabel gainToLabel;
    private javax.swing.JButton generateButton;
    private javax.swing.JLayeredPane generationLayeredPane;
    private javax.swing.JLabel generationSettingsLabel;
    private javax.swing.JPanel generationSettingsPanel;
    private javax.swing.JSeparator generationSettingsSeparator1;
    private javax.swing.JPanel graphPane;
    private javax.swing.JComboBox<String> groupComboBox;
    private javax.swing.JLabel groupSettingLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane listPane;
    private javax.swing.JPanel listSettingsPanel;
    private javax.swing.JSeparator listSettingsSeparator;
    private javax.swing.JFormattedTextField lossEndField;
    private javax.swing.JLabel lossLabel;
    private javax.swing.JFormattedTextField lossStartField;
    private javax.swing.JLabel lossToLabel;
    private javax.swing.JComboBox<String> mainActorComboBox;
    private javax.swing.JLabel mainActorLabel;
    private javax.swing.JSplitPane mainPane;
    private javax.swing.JComboBox<String> needComboBox;
    private javax.swing.JFormattedTextField needEndField;
    private javax.swing.JLabel needLabel;
    private javax.swing.JFormattedTextField needStartField;
    private javax.swing.JLabel needToLabel;
    private javax.swing.JLabel occuringLabel;
    private javax.swing.JLabel placeholderLabel;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel rankingSettingLabel;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel resultCountLabel;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JComboBox<String> sortComboBox;
    private javax.swing.JLabel timesLabel;
    private javax.swing.JSplitPane topPane;
    private javax.swing.JTree tree;
    private DefaultMutableTreeNode root;
    private DefaultTreeModel treeModel;
    private javax.swing.JSplitPane visualizationPane;
    // End of variables declaration//GEN-END:variables
}
